### ISSUE TITLE
rename conda env to 'deforum'

### ISSUE THREAD

**Issue by MrPalais** [osi1880vr/deforum-sd-ui#38]
rename conda env to 'deforum'please, because I'm still using hkly webui and it was already ldm.

thanks

**Comment by MrPalais** [comment]
so run.cmd becomes : 

conda activate deforum && python -m streamlit run scripts\webui_streamlit.py --theme.base dark

**Comment by osi1880vr** [comment]
Hello,

 

we could do so, but please consider, any name we choose can be taken already, so at the moment I advice to rename it yourself and try to keep track.

 

Cheers

Osi

 

Von: MrPalais ***@***.***> 
Gesendet: Donnerstag, 29. September 2022 08:45
An: osi1880vr/deforum-sd-ui ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [osi1880vr/deforum-sd-ui] rename conda env to 'deforum' (Issue #38)

 

rename conda env to 'deforum'please, because I'm still using hkly webui and it was already ldm.

thanks
